# --- CENTRALV specific parameters ---

action_selector: "multinomial"
epsilon_start: .0
epsilon_finish: .0
epsilon_anneal_time: 100000
mask_before_softmax: True

runner: "parallel"

buffer_size: 32
batch_size_run: 8
batch_size: 32
accumulated_episodes: 4

mac: 'basic_mac'
agent: 'rnn'
t_max: 10050000

obs_agent_id: True

lr: 0.001
critic_coef: 1
entropy: 0.01
gae_lambda: 0.95
mini_epochs: 5
eps_clip: 0.2
save_probs: True

agent_output_type: "pi_logits"
learner: "ppo_learner"

name: "mappo_env=8_adam_gae" # no value clip, network init and other tricks ....
