
env: particle

test_greedy: True
test_nepisode: 32
test_interval: 1000
log_interval: 1000
runner_log_interval: 1000
learner_log_interval: 1000
t_max: 50000

obs_last_action: True

env_args:
  map_name: particle
  benchmark: False
  scenario: "simple_tag_coop"
  episode_limit: 25
  state_mode: "all"
  agent_view_radius: 1.5
  score_function: "min"
  partial_obs: True